#!/usr/bin/env python3
import argparse
import pathlib
import re


FNV64_OFFSET = 0x14650FB0739D0383
FNV64_PRIME = 0x100000001B3


def fnv1a64(data: bytes) -> int:
    h = FNV64_OFFSET
    for b in data:
        h ^= b
        h = (h * FNV64_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def parse_signature_enum(facet_h: pathlib.Path) -> list[tuple[str, int]]:
    text = facet_h.read_text(encoding="utf-8")
    m = re.search(r"typedef\s+enum\s+steel_signature_type\s*\{(?P<body>.*?)\}\s*steel_signature_type_t\s*;", text, re.S)
    if not m:
        raise ValueError("failed to find steel_signature_type enum")
    body = m.group("body")

    entries: list[tuple[str, int]] = []
    values: dict[str, int] = {}
    next_value = 0
    for raw in body.split(","):
        line = raw.strip()
        if not line:
            continue
        line = re.sub(r"/\*.*?\*/", "", line).strip()
        if not line:
            continue
        if "=" in line:
            name, rhs = [x.strip() for x in line.split("=", 1)]
            if rhs in values:
                value = values[rhs]
            else:
                value = int(rhs, 0)
        else:
            name = line
            value = next_value
        entries.append((name, value))
        values[name] = value
        next_value = value + 1
    return entries


def compute_type_table_hash(enum_entries: list[tuple[str, int]]) -> int:
    payload = bytearray()
    payload += b"steel.type_table.v1\x00"
    for name, value in enum_entries:
        payload += name.encode("ascii")
        payload += b"="
        payload += str(value).encode("ascii")
        payload += b";"
    return fnv1a64(bytes(payload))


def compute_layout_hash() -> int:
    layout_lines = [
        "steel.manifest.v1",
        "magic:u32",
        "abi_major:u16",
        "abi_minor:u16",
        "host_layout_hash:u64",
        "type_table_hash:u64",
        "memory_min_pages:u32",
        "memory_max_pages:u32",
        "requested_permissions:u32",
        "requested_region_bytes:u32",
        "facet_count:u32",
        "method_count:u32",
        "object_type_count:u32",
        "facet:id[16],method_start:u32,method_count:u32,requested_permissions:u32",
        "method:facet_index:u32,method_id:u32,param_count:u16,reserved:u16,signature_type_hash:u64,param_types:u16[],result_type:u16",
        "object_type:name_len:u16,name:utf8,facet_count:u16,facet_indices:u32[]",
        "attestation:component_sha256[32],signer_id_len:u16,signer_id:utf8,signature_len:u16,signature:bytes",
    ]
    payload = ("\n".join(layout_lines)).encode("ascii")
    return fnv1a64(payload)


def write_c_header(path: pathlib.Path, layout_hash: int, type_table_hash: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""/* Auto-generated by scripts/generate_abi_hashes.py. Do not edit manually. */
#ifndef STEEL_ABI_HASHES_H
#define STEEL_ABI_HASHES_H

#include <stdint.h>

#define STEEL_EXPECTED_LAYOUT_HASH UINT64_C(0x{layout_hash:016x})
#define STEEL_EXPECTED_TYPE_TABLE_HASH UINT64_C(0x{type_table_hash:016x})

#endif
"""
    path.write_text(text, encoding="utf-8")


def write_python_module(path: pathlib.Path, layout_hash: int, type_table_hash: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Auto-generated by scripts/generate_abi_hashes.py. Do not edit manually.
HOST_LAYOUT_HASH = 0x{layout_hash:016X}
TYPE_TABLE_HASH = 0x{type_table_hash:016X}
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate expected ABI hash constants for C host + plugin embed scripts.")
    parser.add_argument("--facet-header", default="include/steel/facet.h")
    parser.add_argument("--c-out", default="include/steel/abi_hashes.h")
    parser.add_argument("--py-out", default="plugins/echo-plugin/scripts/abi_hashes_generated.py")
    args = parser.parse_args()

    facet_header = pathlib.Path(args.facet_header)
    enum_entries = parse_signature_enum(facet_header)
    layout_hash = compute_layout_hash()
    type_table_hash = compute_type_table_hash(enum_entries)
    write_c_header(pathlib.Path(args.c_out), layout_hash, type_table_hash)
    write_python_module(pathlib.Path(args.py_out), layout_hash, type_table_hash)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
