/* Auto-generated by scripts/generate_abi_hashes.py. Do not edit manually. */
#ifndef STEEL_ABI_HASHES_H
#define STEEL_ABI_HASHES_H

#include <stdint.h>

#define STEEL_EXPECTED_LAYOUT_HASH UINT64_C(0xee9dc09b9388456a)
#define STEEL_EXPECTED_TYPE_TABLE_HASH UINT64_C(0x996500dd8a3e71c9)

#endif
