#ifndef STEEL_POLICY_CONFIG_H
#define STEEL_POLICY_CONFIG_H

#include "steel/abi_hashes.h"
#include "steel/plugin_manifest.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef STEEL_POLICY_EXPECTED_LAYOUT_HASH
#define STEEL_POLICY_EXPECTED_LAYOUT_HASH STEEL_EXPECTED_LAYOUT_HASH
#endif

#ifndef STEEL_POLICY_EXPECTED_TYPE_TABLE_HASH
#define STEEL_POLICY_EXPECTED_TYPE_TABLE_HASH STEEL_EXPECTED_TYPE_TABLE_HASH
#endif

#ifndef STEEL_POLICY_MIN_ABI_MINOR
#define STEEL_POLICY_MIN_ABI_MINOR 0u
#endif

#ifndef STEEL_POLICY_MAX_MEMORY_PAGES
#define STEEL_POLICY_MAX_MEMORY_PAGES 64u
#endif

#ifndef STEEL_POLICY_DEFAULT_PLUGIN_REGION_BYTES
#define STEEL_POLICY_DEFAULT_PLUGIN_REGION_BYTES STEEL_DEFAULT_PLUGIN_REGION_BYTES
#endif

#ifndef STEEL_POLICY_MAX_PLUGIN_REGION_BYTES
#define STEEL_POLICY_MAX_PLUGIN_REGION_BYTES (256u * 1024u)
#endif

#ifndef STEEL_POLICY_ALLOWED_PLUGIN_PERMISSIONS
#define STEEL_POLICY_ALLOWED_PLUGIN_PERMISSIONS STEEL_PLUGIN_PERM_ALLOW_HOST_INPUT_COPYBACK
#endif

#ifndef STEEL_POLICY_REQUIRED_SIGNER_ID
#define STEEL_POLICY_REQUIRED_SIGNER_ID "demo-dev"
#endif

#ifndef STEEL_POLICY_TRUSTED_ATTESTATION_PUBLIC_KEY_PATH
#define STEEL_POLICY_TRUSTED_ATTESTATION_PUBLIC_KEY_PATH "plugins/echo-plugin/keys/demo_public.pem"
#endif

#ifndef STEEL_POLICY_HOST_USER_ID
#define STEEL_POLICY_HOST_USER_ID "*"
#endif

#ifndef STEEL_POLICY_USE_PERMISSION_RULES
#define STEEL_POLICY_USE_PERMISSION_RULES 1
#endif

void steel_policy_apply_compile_time(steel_policy_t *policy);

#ifdef __cplusplus
}
#endif

#endif
